# **Limpeza e Preparação dos dados**

Este caderno tem como função organizar os dados para serem trabalhados posteriormente nas análises de dados.

# Como faremos o processo?

* Importaremos os dados brutos neste notebook;
* Limparemos e trataremos os dados para uso;
* Geraremos uma nova base de dados com os dados tratados;

# **Preparando o ambiente**

In [2]:
# Importando bibliotecas a serem utilizadas no arquivo

import pandas as pd

In [3]:
# Clonando o repositório para utilização neste notebook

!git clone https://github.com/iggorbrito/DataAnalysis.git

fatal: destination path 'DataAnalysis' already exists and is not an empty directory.

# **Tratamento dos Dados**

In [19]:
# Importando os dados do arquivo.csv

df = pd.read_csv('/content/DataAnalysis/hospitalar_production/arquivos/dados_brutos_prod_hosp.csv',
            sep=';',
            skiprows=3,
            skipfooter=12,
            thousands='.',
            decimal=','
            )

df.head()

<ipython-input-19-7c4d9ab30df1>:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  df = pd.read_csv('/content/DataAnalysis/hospitalar_production/arquivos/dados_brutos_prod_hosp.csv',

,Região/Unidade da Federação,1992/Mar,1992/Abr,1993/Mai,1993/Dez,1994/Jan,1994/Fev,1994/Mai,1994/Ago,1994/Nov,...,2023/Jan,2023/Fev,2023/Mar,2023/Abr,2023/Mai,2023/Jun,2023/Jul,2023/Ago,2023/Set,Total
0,Região Norte,-,-,-,-,-,-,-,-,-,...,96172468.20,89179013.24,1.077103e+08,1.029894e+08,1.113583e+08,1.018417e+08,84453525.15,63438531.28,23727101.73,1.275658e+10
1,.. Rondônia,-,-,-,-,-,-,-,-,-,...,10740989.45,10016556.60,1.229328e+07,1.221936e+07,1.189019e+07,1.066533e+07,8605286.31,6663659.44,3096431.87,1.347655e+09
2,.. Acre,-,-,-,-,-,-,-,-,-,...,4031485.58,3681605.49,4.621769e+06,4.396295e+06,4.782590e+06,4.942018e+06,3825134.08,2036113.50,-,5.703918e+08
3,.. Amazonas,-,-,-,-,-,-,-,-,-,...,18240136.15,18092793.18,2.088737e+07,2.107829e+07,2.281670e+07,2.225392e+07,20493652.36,14405538.40,4808719.64,2.544018e+09
4,.. Roraima,-,-,-,-,-,-,-,-,-,...,3970057.61,3568884.82,5.034623e+06,4.214755e+06,4.264413e+06,2.728020e+06,1679054.65,725887.92,12258.26,4.397403e+08

In [20]:
df.info

<bound method DataFrame.info of    Região/Unidade da Federação  1992/Mar  1992/Abr  1993/Mai  1993/Dez  \
0                 Região Norte         -         -         -         -
1                  .. Rondônia         -         -         -         -
2                      .. Acre         -         -         -         -
3                  .. Amazonas         -         -         -         -
4                   .. Roraima         -         -         -         -
5                      .. Pará         -         -         -         -
6                     .. Amapá         -         -         -         -
7                 .. Tocantins         -         -         -         -
8              Região Nordeste         -         -         -         -
9                  .. Maranhão         -         -         -         -
10                    .. Piauí         -         -         -         -
11                    .. Ceará         -         -         -         -
12      .. Rio Grande do Norte         -         -         -         -
13                  .. Paraíba         -         -         -         -
14               .. Pernambuco         -         -         -         -
15                  .. Alagoas         -         -         -         -
16                  .. Sergipe         -         -         -         -
17                    .. Bahia         -         -         -         -
18              Região Sudeste  40243.16  11449.99  34583.77  68556.52
19             .. Minas Gerais         -         -         -         -
20           .. Espírito Santo         -         -         -         -
21           .. Rio de Janeiro         -         -         -         -
22                .. São Paulo  40243.16  11449.99  34583.77  68556.52
23                  Região Sul         -         -         -         -
24                   .. Paraná         -         -         -         -
25           .. Santa Catarina         -         -         -         -
26        .. Rio Grande do Sul         -         -         -         -
27         Região Centro-Oeste         -         -         -         -
28       .. Mato Grosso do Sul         -         -         -         -
29              .. Mato Grosso         -         -         -         -
30                    .. Goiás         -         -         -         -
31         .. Distrito Federal         -         -         -         -

    1994/Jan  1994/Fev  1994/Mai  1994/Ago  1994/Nov  ...      2023/Jan  \
0          -         -         -         -         -  ...  9.617247e+07
1          -         -         -         -         -  ...  1.074099e+07
2          -         -         -         -         -  ...  4.031486e+06
3          -         -         -         -         -  ...  1.824014e+07
4          -         -         -         -         -  ...  3.970058e+06
5          -         -         -         -         -  ...  4.823441e+07
6          -         -         -         -         -  ...  3.154660e+06
7          -         -         -         -         -  ...  7.800731e+06
8          -         -         -         -         -  ...  3.723394e+08
9          -         -         -         -         -  ...  3.888770e+07
10         -         -         -         -         -  ...  2.088638e+07
11         -         -         -         -         -  ...  6.340790e+07
12         -         -         -         -         -  ...  2.550861e+07
13         -         -         -         -         -  ...  2.362056e+07
14         -         -         -         -         -  ...  7.796420e+07
15         -         -         -         -         -  ...  1.697589e+07
16         -         -         -         -         -  ...  1.435935e+07
17         -         -         -         -         -  ...  9.072880e+07
18  39809.34  19904.67  19904.67  34532.40  23374.12  ...  7.090728e+08
19         -         -         -         -         -  ...  1.980409e+08
20         -         -         -         -         -  ...  3.739060e+07
21         -         -         -         -         -  ...  1.108898e+08
22  39809.34  19904.67  19904.67  34532.40  23374.12  ...  3.627515e+08
23         -         -         -         -         -  ...  3.267136e+08
24         -         -         -         -         -  ...  1.382448e+08
25         -         -         -         -         -  ...  7.948850e+07
26         -         -         -         -         -  ...  1.089802e+08
27         -         -         -         -         -  ...  1.227958e+08
28         -         -         -         -         -  ...  2.481715e+07
29         -         -         -         -         -  ...  2.184596e+07
30         -         -         -         -         -  ...  4.683776e+07
31         -         -         -         -         -  ...  2.929489e+07

        2023/Fev      2023/Mar      2023/Abr      2023/Mai      2023/Jun  \
0   8.917901e+07  1.077103e+08  1.029894e+08  1.113583e+08  1.018417e+08
1   1.001656e+07  1.229328e+07  1.221936e+07  1.189019e+07  1.066533e+07
2   3.681605e+06  4.621769e+06  4.396295e+06  4.782590e+06  4.942018e+06
3   1.809279e+07  2.088737e+07  2.107829e+07  2.281670e+07  2.225392e+07
4   3.568885e+06  5.034623e+06  4.214755e+06  4.264413e+06  2.728020e+06
5   4.351351e+07  5.093844e+07  4.814882e+07  5.221103e+07  4.777753e+07
6   2.996757e+06  4.543352e+06  4.604624e+06  5.777218e+06  5.493104e+06
7   7.308901e+06  9.391510e+06  8.327289e+06  9.616159e+06  7.981780e+06
8   3.350517e+08  4.019642e+08  3.700385e+08  4.121007e+08  3.783376e+08
9   3.405347e+07  4.065582e+07  3.721534e+07  4.073586e+07  3.837912e+07
10  1.884241e+07  2.259740e+07  2.102192e+07  2.423419e+07  2.204339e+07
11  5.563987e+07  6.694084e+07  6.164048e+07  6.791848e+07  6.064564e+07
12  2.426293e+07  2.909382e+07  2.636055e+07  3.022152e+07  2.845902e+07
13  2.178310e+07  2.634831e+07  2.525588e+07  2.711938e+07  2.612860e+07
14  7.057516e+07  8.266643e+07  7.669114e+07  8.512667e+07  8.248713e+07
15  1.484172e+07  1.870322e+07  1.758684e+07  1.944448e+07  1.824951e+07
16  1.313112e+07  1.510573e+07  1.449237e+07  1.538014e+07  1.380652e+07
17  8.192196e+07  9.985268e+07  8.977401e+07  1.019200e+08  8.813868e+07
18  6.392614e+08  7.577993e+08  7.026543e+08  7.680827e+08  7.153465e+08
19  1.816823e+08  2.166145e+08  1.990258e+08  2.213974e+08  2.041501e+08
20  3.491644e+07  4.198081e+07  3.876710e+07  4.304856e+07  3.968853e+07
21  9.730622e+07  1.196223e+08  1.126085e+08  1.214459e+08  1.123344e+08
22  3.253564e+08  3.795817e+08  3.522529e+08  3.821908e+08  3.591735e+08
23  2.996592e+08  3.616931e+08  3.330825e+08  3.665877e+08  3.435607e+08
24  1.281119e+08  1.547534e+08  1.406049e+08  1.555776e+08  1.462044e+08
25  7.453248e+07  8.729510e+07  8.471040e+07  9.197288e+07  8.689808e+07
26  9.701482e+07  1.196447e+08  1.077672e+08  1.190372e+08  1.104582e+08
27  1.110225e+08  1.291795e+08  1.207024e+08  1.284736e+08  1.180002e+08
28  2.272217e+07  2.706703e+07  2.483241e+07  2.653713e+07  2.354477e+07
29  2.001216e+07  2.326044e+07  2.182816e+07  2.381600e+07  2.152080e+07
30  4.329442e+07  4.987450e+07  4.561723e+07  4.824487e+07  4.492439e+07
31  2.499377e+07  2.897752e+07  2.842458e+07  2.987563e+07  2.801029e+07

        2023/Jul      2023/Ago      2023/Set         Total
0   8.445353e+07  6.343853e+07   23727101.73  1.275658e+10
1   8.605286e+06  6.663659e+06    3096431.87  1.347655e+09
2   3.825134e+06  2.036114e+06             -  5.703918e+08
3   2.049365e+07  1.440554e+07    4808719.64  2.544018e+09
4   1.679055e+06  7.258879e+05      12258.26  4.397403e+08
5   4.148396e+07  3.396834e+07   14279221.73  6.108475e+09
6   3.073655e+06  2.792864e+06    1160640.47  4.195544e+08
7   5.292783e+06  2.846132e+06     369829.76  1.326740e+09
8   3.555749e+08  3.026691e+08  144625039.01  5.193356e+10
9   3.088958e+07  2.297393e+07   10514699.51  5.072947e+09
10  2.209911e+07  1.905126e+07   10289536.54  2.967330e+09
11  5.371135e+07  4.090694e+07   18766559.28  8.592849e+09
12  2.673468e+07  2.344333e+07   10360868.54  3.526415e+09
13  2.701475e+07  2.248790e+07   10763250.60  3.389247e+09
14  8.148690e+07  7.814669e+07   36890256.15  1.120231e+10
15  1.736161e+07  1.439781e+07    8007519.01  2.832040e+09
16  9.510138e+06  6.608875e+06    2815251.70  1.638960e+09
17  8.676681e+07  7.465236e+07   36217097.68  1.271146e+10
18  6.668156e+08  5.854173e+08  301094431.78  9.801154e+10
19  1.860960e+08  1.583551e+08   78647255.47  2.670485e+10
20  3.668118e+07  2.937136e+07   13326173.33  4.617108e+09
21  1.019115e+08  8.302126e+07   42421765.65  1.378811e+10
22  3.421268e+08  3.146695e+08  166699237.33  5.290147e+10
23  3.055465e+08  2.566057e+08  115007434.58  4.581751e+10
24  1.287195e+08  1.150858e+08   59429193.44  1.914311e+10
25  7.754281e+07  6.063702e+07   26899524.83  1.040234e+10
26  9.928424e+07  8.088286e+07   28678716.31  1.627206e+10
27  1.082574e+08  8.780667e+07   44284327.84  1.590997e+10
28  1.984138e+07  1.193048e+07    4101485.00  3.114266e+09
29  1.930400e+07  1.478932e+07    6199538.89  2.894733e+09
30  4.280007e+07  3.697049e+07   19454124.86  6.479238e+09
31  2.631196e+07  2.411637e+07   14529179.09  3.421733e+09

[32 rows x 317 columns]>

In [24]:
# Define o formato de exibição para números de ponto flutuante

pd.options.display.float_format='{:.2f}'.format

df.head()

,Região/Unidade da Federação,1992/Mar,1992/Abr,1993/Mai,1993/Dez,1994/Jan,1994/Fev,1994/Mai,1994/Ago,1994/Nov,...,2023/Jan,2023/Fev,2023/Mar,2023/Abr,2023/Mai,2023/Jun,2023/Jul,2023/Ago,2023/Set,Total
0,Região Norte,-,-,-,-,-,-,-,-,-,...,96172468.20,89179013.24,107710343.07,102989429.23,111358306.41,101841697.42,84453525.15,63438531.28,23727101.73,12756575136.73
1,.. Rondônia,-,-,-,-,-,-,-,-,-,...,10740989.45,10016556.60,12293282.07,12219359.19,11890194.03,10665326.68,8605286.31,6663659.44,3096431.87,1347654616.11
2,.. Acre,-,-,-,-,-,-,-,-,-,...,4031485.58,3681605.49,4621768.84,4396294.92,4782589.78,4942017.56,3825134.08,2036113.50,-,570391786.05
3,.. Amazonas,-,-,-,-,-,-,-,-,-,...,18240136.15,18092793.18,20887366.24,21078288.95,22816701.33,22253915.19,20493652.36,14405538.40,4808719.64,2544018144.24
4,.. Roraima,-,-,-,-,-,-,-,-,-,...,3970057.61,3568884.82,5034623.41,4214754.88,4264412.63,2728019.67,1679054.65,725887.92,12258.26,439740344.01

In [33]:
# Remover colunas que não tem todos os valores dos meses

colunas_usaveis = df.mean().index.tolist()
colunas_usaveis.insert(0, "Região/Unidade da Federação")

colunas_usaveis[:5]

<ipython-input-33-2dfcfe2b990d>:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  colunas_usaveis = df.mean().index.tolist()

['Região/Unidade da Federação', '2007/Ago', '2007/Set', '2007/Out', '2007/Nov']

In [34]:
# Dados usáveis

dados_usaveis = df[colunas_usaveis]

dados_usaveis.head()

,Região/Unidade da Federação,2007/Ago,2007/Set,2007/Out,2007/Nov,2007/Dez,2008/Jan,2008/Fev,2008/Mar,2008/Abr,...,2022/Dez,2023/Jan,2023/Fev,2023/Mar,2023/Abr,2023/Mai,2023/Jun,2023/Jul,2023/Ago,Total
0,Região Norte,274163.86,702698.79,3034989.40,9438700.38,24930500.29,44017418.18,38844188.02,42058042.63,43806481.51,...,92543696.46,96172468.20,89179013.24,107710343.07,102989429.23,111358306.41,101841697.42,84453525.15,63438531.28,12756575136.73
1,.. Rondônia,4209.37,16397.03,133645.19,346912.84,711758.31,1829559.71,1940792.63,1955721.68,2143353.81,...,10171206.31,10740989.45,10016556.60,12293282.07,12219359.19,11890194.03,10665326.68,8605286.31,6663659.44,1347654616.11
2,.. Acre,10470.07,14001.71,86200.85,301323.68,769612.36,1731744.62,1743978.66,2057439.02,2057829.69,...,3956231.61,4031485.58,3681605.49,4621768.84,4396294.92,4782589.78,4942017.56,3825134.08,2036113.50,570391786.05
3,.. Amazonas,35752.72,45570.64,416012.30,2020381.79,5949408.99,11419210.08,7934652.10,8641517.13,8531576.49,...,18254068.20,18240136.15,18092793.18,20887366.24,21078288.95,22816701.33,22253915.19,20493652.36,14405538.40,2544018144.24
4,.. Roraima,4785.91,11858.63,43852.67,369328.51,470676.43,808448.39,771687.83,876091.18,896952.53,...,3837710.72,3970057.61,3568884.82,5034623.41,4214754.88,4264412.63,2728019.67,1679054.65,725887.92,439740344.01

In [39]:
# Removendo a couna de total
dados_usaveis = dados_usaveis.drop("Total", axis=1)

dados_usaveis.head()

,Região/Unidade da Federação,2007/Ago,2007/Set,2007/Out,2007/Nov,2007/Dez,2008/Jan,2008/Fev,2008/Mar,2008/Abr,...,2022/Nov,2022/Dez,2023/Jan,2023/Fev,2023/Mar,2023/Abr,2023/Mai,2023/Jun,2023/Jul,2023/Ago
0,Região Norte,274163.86,702698.79,3034989.40,9438700.38,24930500.29,44017418.18,38844188.02,42058042.63,43806481.51,...,95780606.94,92543696.46,96172468.20,89179013.24,107710343.07,102989429.23,111358306.41,101841697.42,84453525.15,63438531.28
1,.. Rondônia,4209.37,16397.03,133645.19,346912.84,711758.31,1829559.71,1940792.63,1955721.68,2143353.81,...,10172549.54,10171206.31,10740989.45,10016556.60,12293282.07,12219359.19,11890194.03,10665326.68,8605286.31,6663659.44
2,.. Acre,10470.07,14001.71,86200.85,301323.68,769612.36,1731744.62,1743978.66,2057439.02,2057829.69,...,4029748.15,3956231.61,4031485.58,3681605.49,4621768.84,4396294.92,4782589.78,4942017.56,3825134.08,2036113.50
3,.. Amazonas,35752.72,45570.64,416012.30,2020381.79,5949408.99,11419210.08,7934652.10,8641517.13,8531576.49,...,19430986.32,18254068.20,18240136.15,18092793.18,20887366.24,21078288.95,22816701.33,22253915.19,20493652.36,14405538.40
4,.. Roraima,4785.91,11858.63,43852.67,369328.51,470676.43,808448.39,771687.83,876091.18,896952.53,...,4672985.43,3837710.72,3970057.61,3568884.82,5034623.41,4214754.88,4264412.63,2728019.67,1679054.65,725887.92

# **Gerando novo arquivo**

In [41]:
# Gerando o arquivo e inserindo no diretório

dados_tratados = '/content/DataAnalysis/hospitalar_production/arquivos/dados_tratados.csv'

dados_usaveis.to_csv(dados_tratados, index=False)